language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly
    - hhvm

notifications:
  email: false

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --verbose

